name: Trigger auto deployment for container-app-75dk32bi3pdau

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-75dk32bi3pdau-AutoDeployTrigger-2bd96bc2-b760-4a23-bb3a-678c02d73072.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP75DK32BI3PDAU_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP75DK32BI3PDAU_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP75DK32BI3PDAU_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPP75DK32BI3PDAU_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP75DK32BI3PDAU_REGISTRY_PASSWORD }}
          containerAppName: container-app-75dk32bi3pdau
          resourceGroup: appspacetest
          imageToBuild: default/container-app-75dk32bi3pdau:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


