name: Trigger auto deployment for container-app-esbgvcu4yypzw

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-esbgvcu4yypzw-AutoDeployTrigger-785385ba-b495-4b0b-997e-ec46622a723e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPESBGVCU4YYPZW_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPESBGVCU4YYPZW_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPESBGVCU4YYPZW_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPESBGVCU4YYPZW_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPESBGVCU4YYPZW_REGISTRY_PASSWORD }}
          containerAppName: container-app-esbgvcu4yypzw
          resourceGroup: todonodejspgsqlgoogleauthb58f8707
          imageToBuild: default/container-app-esbgvcu4yypzw:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


